/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as RecoverPasswordRouteImport } from './routes/recover-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as LayoutRouteImport } from './routes/_layout'
import { Route as LayoutIndexRouteImport } from './routes/_layout/index'
import { Route as LayoutSettingsRouteImport } from './routes/_layout/settings'
import { Route as LayoutReportesRouteImport } from './routes/_layout/reportes'
import { Route as LayoutRecepcionesRouteImport } from './routes/_layout/recepciones'
import { Route as LayoutProveedoresRouteImport } from './routes/_layout/proveedores'
import { Route as LayoutProductosRouteImport } from './routes/_layout/productos'
import { Route as LayoutLotesRouteImport } from './routes/_layout/lotes'
import { Route as LayoutItemsRouteImport } from './routes/_layout/items'
import { Route as LayoutFabricantesRouteImport } from './routes/_layout/fabricantes'
import { Route as LayoutAdminRouteImport } from './routes/_layout/admin'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const RecoverPasswordRoute = RecoverPasswordRouteImport.update({
  id: '/recover-password',
  path: '/recover-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutRoute = LayoutRouteImport.update({
  id: '/_layout',
  getParentRoute: () => rootRouteImport,
} as any)
const LayoutIndexRoute = LayoutIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutSettingsRoute = LayoutSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutReportesRoute = LayoutReportesRouteImport.update({
  id: '/reportes',
  path: '/reportes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutRecepcionesRoute = LayoutRecepcionesRouteImport.update({
  id: '/recepciones',
  path: '/recepciones',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProveedoresRoute = LayoutProveedoresRouteImport.update({
  id: '/proveedores',
  path: '/proveedores',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutProductosRoute = LayoutProductosRouteImport.update({
  id: '/productos',
  path: '/productos',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutLotesRoute = LayoutLotesRouteImport.update({
  id: '/lotes',
  path: '/lotes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutItemsRoute = LayoutItemsRouteImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutFabricantesRoute = LayoutFabricantesRouteImport.update({
  id: '/fabricantes',
  path: '/fabricantes',
  getParentRoute: () => LayoutRoute,
} as any)
const LayoutAdminRoute = LayoutAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => LayoutRoute,
} as any)

export interface FileRoutesByFullPath {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/fabricantes': typeof LayoutFabricantesRoute
  '/items': typeof LayoutItemsRoute
  '/lotes': typeof LayoutLotesRoute
  '/productos': typeof LayoutProductosRoute
  '/proveedores': typeof LayoutProveedoresRoute
  '/recepciones': typeof LayoutRecepcionesRoute
  '/reportes': typeof LayoutReportesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesByTo {
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin': typeof LayoutAdminRoute
  '/fabricantes': typeof LayoutFabricantesRoute
  '/items': typeof LayoutItemsRoute
  '/lotes': typeof LayoutLotesRoute
  '/productos': typeof LayoutProductosRoute
  '/proveedores': typeof LayoutProveedoresRoute
  '/recepciones': typeof LayoutRecepcionesRoute
  '/reportes': typeof LayoutReportesRoute
  '/settings': typeof LayoutSettingsRoute
  '/': typeof LayoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_layout': typeof LayoutRouteWithChildren
  '/login': typeof LoginRoute
  '/recover-password': typeof RecoverPasswordRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/_layout/admin': typeof LayoutAdminRoute
  '/_layout/fabricantes': typeof LayoutFabricantesRoute
  '/_layout/items': typeof LayoutItemsRoute
  '/_layout/lotes': typeof LayoutLotesRoute
  '/_layout/productos': typeof LayoutProductosRoute
  '/_layout/proveedores': typeof LayoutProveedoresRoute
  '/_layout/recepciones': typeof LayoutRecepcionesRoute
  '/_layout/reportes': typeof LayoutReportesRoute
  '/_layout/settings': typeof LayoutSettingsRoute
  '/_layout/': typeof LayoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/fabricantes'
    | '/items'
    | '/lotes'
    | '/productos'
    | '/proveedores'
    | '/recepciones'
    | '/reportes'
    | '/settings'
    | '/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/admin'
    | '/fabricantes'
    | '/items'
    | '/lotes'
    | '/productos'
    | '/proveedores'
    | '/recepciones'
    | '/reportes'
    | '/settings'
    | '/'
  id:
    | '__root__'
    | '/_layout'
    | '/login'
    | '/recover-password'
    | '/reset-password'
    | '/signup'
    | '/_layout/admin'
    | '/_layout/fabricantes'
    | '/_layout/items'
    | '/_layout/lotes'
    | '/_layout/productos'
    | '/_layout/proveedores'
    | '/_layout/recepciones'
    | '/_layout/reportes'
    | '/_layout/settings'
    | '/_layout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  LayoutRoute: typeof LayoutRouteWithChildren
  LoginRoute: typeof LoginRoute
  RecoverPasswordRoute: typeof RecoverPasswordRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/recover-password': {
      id: '/recover-password'
      path: '/recover-password'
      fullPath: '/recover-password'
      preLoaderRoute: typeof RecoverPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout': {
      id: '/_layout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof LayoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_layout/': {
      id: '/_layout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof LayoutIndexRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/settings': {
      id: '/_layout/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof LayoutSettingsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/reportes': {
      id: '/_layout/reportes'
      path: '/reportes'
      fullPath: '/reportes'
      preLoaderRoute: typeof LayoutReportesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/recepciones': {
      id: '/_layout/recepciones'
      path: '/recepciones'
      fullPath: '/recepciones'
      preLoaderRoute: typeof LayoutRecepcionesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/proveedores': {
      id: '/_layout/proveedores'
      path: '/proveedores'
      fullPath: '/proveedores'
      preLoaderRoute: typeof LayoutProveedoresRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/productos': {
      id: '/_layout/productos'
      path: '/productos'
      fullPath: '/productos'
      preLoaderRoute: typeof LayoutProductosRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/lotes': {
      id: '/_layout/lotes'
      path: '/lotes'
      fullPath: '/lotes'
      preLoaderRoute: typeof LayoutLotesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/items': {
      id: '/_layout/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof LayoutItemsRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/fabricantes': {
      id: '/_layout/fabricantes'
      path: '/fabricantes'
      fullPath: '/fabricantes'
      preLoaderRoute: typeof LayoutFabricantesRouteImport
      parentRoute: typeof LayoutRoute
    }
    '/_layout/admin': {
      id: '/_layout/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof LayoutAdminRouteImport
      parentRoute: typeof LayoutRoute
    }
  }
}

interface LayoutRouteChildren {
  LayoutAdminRoute: typeof LayoutAdminRoute
  LayoutFabricantesRoute: typeof LayoutFabricantesRoute
  LayoutItemsRoute: typeof LayoutItemsRoute
  LayoutLotesRoute: typeof LayoutLotesRoute
  LayoutProductosRoute: typeof LayoutProductosRoute
  LayoutProveedoresRoute: typeof LayoutProveedoresRoute
  LayoutRecepcionesRoute: typeof LayoutRecepcionesRoute
  LayoutReportesRoute: typeof LayoutReportesRoute
  LayoutSettingsRoute: typeof LayoutSettingsRoute
  LayoutIndexRoute: typeof LayoutIndexRoute
}

const LayoutRouteChildren: LayoutRouteChildren = {
  LayoutAdminRoute: LayoutAdminRoute,
  LayoutFabricantesRoute: LayoutFabricantesRoute,
  LayoutItemsRoute: LayoutItemsRoute,
  LayoutLotesRoute: LayoutLotesRoute,
  LayoutProductosRoute: LayoutProductosRoute,
  LayoutProveedoresRoute: LayoutProveedoresRoute,
  LayoutRecepcionesRoute: LayoutRecepcionesRoute,
  LayoutReportesRoute: LayoutReportesRoute,
  LayoutSettingsRoute: LayoutSettingsRoute,
  LayoutIndexRoute: LayoutIndexRoute,
}

const LayoutRouteWithChildren =
  LayoutRoute._addFileChildren(LayoutRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  LayoutRoute: LayoutRouteWithChildren,
  LoginRoute: LoginRoute,
  RecoverPasswordRoute: RecoverPasswordRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
